version: '3.8'

services:
  api-monitor:
    build: .
    container_name: api_monitor
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo