services:
  datadog-node_app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DD_SERVICE: datadog-node_app
      DD_ENV: dev
      DD_VERSION: 1.0.0
      DD_AGENT_HOST: datadog-agent
      DD_DOGSTATSD_PORT: 8125
    depends_on:
      - datadog-agent
  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_HOSTNAME: "datadog-agent"
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_LOGS_ENABLED: "true"
    ports:
      - "8126:8126"
      - "8125:8125/udp"